### ISSUE TITLE
Add support for Inpainting 

### ISSUE THREAD

**Issue by mspronesti** [LaurentMazare/diffusers-rs#10]
This is a feature request to support the inpainting pipeline. I will be probably work on this in the following days, unless somebody comes up with an implementation first.

**Comment by LaurentMazare** [comment]
I've added an inpainting pipeline/example and it seems to work fine on the examples that I've tried. You can see some sample in the [main readme](https://github.com/LaurentMazare/diffusers-rs#inpainting-pipeline).
Note that this requires a different weight files for the unet.

**Comment by makeecat** [comment]
The example of inpainting needs to be fixed from 

`cargo run --example stable-diffusion-inpaint --input-image sd_input.png --mask-image sd_mask.png`

to 

`cargo run --example stable-diffusion-inpaint --features clap -- --input-image sd_input.png --mask-image sd_mask.png`

**Comment by LaurentMazare** [comment]
The readme example should be fixed now, thanks for reporting.
