### ISSUE TITLE
[Question] How do I enable CUDA?

### ISSUE THREAD

**Issue by mushogenshin** [LaurentMazare/diffusers-rs#11]
Thanks so much for your Rust implementation, and especially for the Stable Diffusion example.

I have a noob question: how do I enable CUDA? 

### My problem:
Even though my machine (on Windows):
  - has RTX 3090 graphic cards,
  - has [CUDA](https://developer.nvidia.com/cuda-downloads) installed,

when running the [Stable Diffusion example](https://github.com/LaurentMazare/diffusers-rs/blob/e969b7551b0e1825edf67189e74917bd4d302b2f/examples/stable-diffusion/main.rs) without the arg `--cpu` it still resorts to my CPU instead.

Would someone please kindly help?

**Comment by LaurentMazare** [comment]
Did you install libtorch manually or rely on the automated install? See this [readme](https://github.com/LaurentMazare/tch-rs/#libtorch-manual-install) for more details.
The automated install will default to the cpu version, you can get it to install the cuda enabled libtorch by setting `TORCH_CUDA_VERSION` to something like `cu117` though in the long run it's probably better/more stable to go through the manual install process.

**Comment by mushogenshin** [comment]
Thanks a lot for your pointer. I installed using automated script to get the models converted at first, then after having read the README at `tch-rs` I've followed the instructions there to config the proper env vars. I think I almost got it working except for encountering two linker errors:

```
Creating library E:\projects\diffusers-rs\target\debug\examples\stable_diffusion.lib and object E:\projects\diffusers-rs\target\debug\examples\stable_diffusion.exp
          libtorch_sys-1e4b51fbd71aba4d.rlib(torch_api.o) : error LNK2001: unresolved external symbol __imp___tls_index_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
          libtorch_sys-1e4b51fbd71aba4d.rlib(torch_api.o) : error LNK2001: unresolved external symbol __imp___tls_offset_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
          E:\projects\diffusers-rs\target\debug\examples\stable_diffusion.exe : fatal error LNK1120: 2 unresolved externals


warning: `diffusers` (example "stable-diffusion") generated 17 warnings
error: could not compile `diffusers` due to previous error; 17 warnings emitted
```

(I switched to `libtorch` debug build after seeing the release build generated even more errors, as I recall). But I think this linking issue would belong to the `tch-rs` repo instead, and actually not a biggie for me, as I can wait until things get more stable.

This is an image I generated using CPU for fun:

`"A rusty intimidating robot holding a fire torch, Gustave Courbet"`
![A rusty intimidating robot holding a fire torch, Gustave Courbet](https://i.imgur.com/G8Le5h7.png)

**Comment by LaurentMazare** [comment]
Re the tls error, this has indeed already been reported on the tch side [here](https://github.com/LaurentMazare/tch-rs/issues/563). It seems that the issue is at the libtorch/Visual Studio level [stackoverflow post](https://stackoverflow.com/questions/74366357/updating-to-visual-studio-17-4-0-yields-linker-errors-related-to-tls). The quickest workaround is probably to use an older version of visual studio if you can.
