### ISSUE TITLE
Error: No such file or directory

### ISSUE THREAD

**Issue by sloganking** [LaurentMazare/diffusers-rs#12]
Running 
```
cargo run --example stable-diffusion --features clap -- --prompt "A very rusty robot holding a fire torch." --cpu all
```

Yields 
```
Error: No such file or directory (os error 2)
```

But doesn't tell me what directory is missing. I assume it can't find the model weights but have no idea how to fix. Can this error me made more clear?

**Comment by sloganking** [comment]
I have solved this by following https://github.com/LaurentMazare/diffusers-rs#getting-the-weights-and-vocab-file

But I still think the error message could be made more clear.

**Comment by LaurentMazare** [comment]
Right, I just made some changes so that the error is more explicit and includes the file name (fwiw it's a long standing debate whether the rust standard library should do that by default, see [this issue](https://github.com/rust-lang/rfcs/issues/2885)).

**Comment by sloganking** [comment]
I see it now gives

```
Error: error opening "data/bpe_simple_vocab_16e6.txt"

Caused by:
    No such file or directory (os error 2)
```

I'm happy with this. So I'll close the issue for now.

You might consider linking to your [#getting-the-weights-and-vocab-file](https://github.com/LaurentMazare/diffusers-rs#getting-the-weights-and-vocab-file) section in your readme in the error message, if you want to take it a step further.
