### ISSUE TITLE
Where are the in-progress image files stored?

### ISSUE THREAD

**Issue by JohnAlcatraz** [LaurentMazare/diffusers-rs#13]
The readme mentions this:

> At each step, some sd_*.png image is generated, the last one sd_30.png should be the least noisy one.

I can't find those files anywhere though. I only see the final file called `sd_final.png`.

**Comment by LaurentMazare** [comment]
Ah the readme was actually out of date as this was the case in the very first version but this bit was then removed from the default example. We could add this back if it's helpful but for now I've just fixed the readme.

**Comment by JohnAlcatraz** [comment]
In that case, it would be great if you could add it back, yes! That feature would be very useful for me.

**Comment by JohnAlcatraz** [comment]
I'm still really interested in this feature being added back in.

**Comment by LaurentMazare** [comment]
Sorry for the delay, I've just pushed some changes that add a `--intermediary-images` flag. When set, these images should be generated again.

**Comment by JohnAlcatraz** [comment]
Awesome, thanks!

**Comment by JohnAlcatraz** [comment]
At first glance, the new flag seems to work great, but there is something weird going on with `--intermediary-images`.

Firstly, the two last images it generates seem to always be fully identical. So if I run a generation with `--n-steps 5`, then `sd_final-4.png` and `sd_final-5.png` look fully identical to the eye. The SHA-256 hash of the files is not identical, but they look pixel-perfect identical to the eye.

But what's most weird is, the intermediary images make it look as if the speed at which the image converges seems to change depending on what `--n-steps` you use? That makes no sense at all, but look at this, this is an image generated with `--n-steps 10`:

![image](https://user-images.githubusercontent.com/12215210/210280280-ff35a025-0534-4bc0-a2cd-8a373ac32ca5.png)

You can see the last two images are identical, but more importantly, the first "perfect" looking image is number 9.

But now the magic comes, this is the exact same image generated with `--n-steps 5`:

![image](https://user-images.githubusercontent.com/12215210/210280348-edf14dec-cfbe-4990-ab71-80905b118419.png)

So now, the image looks way better already after just 4 steps, where it was just mostly noise before. How can that be?

The final image generated with `--n-steps 5` looks less good than the final image generated with `--n-steps 10`, so that's as expected. But the first 5 intermediary images should look fully identical in both cases, right? And they certainly don't.

**Comment by LaurentMazare** [comment]
I might be misunderstanding what you say but I wouldn't think the intermediary images should look the same: the scheduler is there to ensure that more progress is made during each step for lower values of `--n-steps` (but as it takes "larger" steps the diffusion process is less precise than with larger `--n-steps` values).

**Comment by JohnAlcatraz** [comment]
Ok, I guess I simply misunderstand how the scheduler works then. So then the only issue is why the two last images generated by `--intermediary-images` always look fully identical, that appears to be a bug. For example, if you run with `--n-steps 2`, you will get two intermediary images and 1 final output image, and they're all fully identical. But there should be at least 2 different images.

**Comment by LaurentMazare** [comment]
With this scheduling process, it's likely for the last step to only make very tiny adjustments so it's unclear to me whether this is expected or not. Could you try comparing this to the python version and see if it happens there too?

**Comment by LaurentMazare** [comment]
Closing this as it has been a while and the main issue adding an option to get the intermediary images has been implemented.
