### ISSUE TITLE
WebAssembly inference example

### ISSUE THREAD

**Issue by aggprakhar** [LaurentMazare/diffusers-rs#14]
Hi, is there an example of using stable diffusion in WebAssembly run time using Wagi / Spin / WasmEdge etc. using GPU and serving modules over https requests? If not, how can I achieve such use case? any help would be appreciated, thanks.

**Comment by Ryu1845** [comment]
Since this library depends on the C++ api of PyTorch. I don't think that's possible.

**Comment by LaurentMazare** [comment]
As mentioned, this is really tricky because of the dependency to libtorch, so closing this for now.
