### ISSUE TITLE
Stable Diffusion 2.0 support

### ISSUE THREAD

**Issue by JohnAlcatraz** [LaurentMazare/diffusers-rs#15]
Will this support Stable Diffusion 2.0?

https://stability.ai/blog/stable-diffusion-v2-release

**Comment by LaurentMazare** [comment]
Much likely yes, I only glimpsed at the code and it doesn't seem to be much different from 1.5, I'll probably wait for this to be integrated in the huggingface diffusers library before giving this a try (there are a couple PR there already that seem related).

**Comment by JohnAlcatraz** [comment]
When I opened this issue the 2.0 announcement just was released, but now with there being some feedback from people who tested 2.0 so far, supporting it really doesn't seem important. It appears to be worse than 1.5, so no need to put effort into 2.0.

**Comment by ajmwagar** [comment]
The SD 2.1 release just dropped. Which may encourage the community to support 2.1 in the future.

https://www.reddit.com/r/StableDiffusion/comments/zf21db/stable_diffusion_21_announcement/

**Comment by LaurentMazare** [comment]
Stable-diffusion 2.1 should be supported though only for txt2img at the moment, I haven't packaged the weight on huggingface yet but there are some indications on how to create these files at the top of the example script.

Running the command below should generate the following pic:
```bash
cargo run --example stable-diffusion-2 --features clap \
    -- --cpu all  --prompt "A rusty robot holding a fire torch in its hand." --num-samples 1
```

![robot-final](https://user-images.githubusercontent.com/1041292/206874934-b5aabc7c-cce8-44d2-a7c2-1030e0032b85.jpg)

**Comment by JohnAlcatraz** [comment]
Nice! Do you notice any speed difference compared to 1.5?

**Comment by LaurentMazare** [comment]
Well for me it's a lot slower as 1.5 could fit on my 8GB 2080 gpu but 2.1 cannot. The cpu version is also slower as the size of the unet increased since 2.1.

**Comment by JohnAlcatraz** [comment]
Ok, interesting. Hopefully soon this will be released and can also be supported by diffusers-rs then: https://twitter.com/EMostaque/status/1598408373170761728

After that 20x speedup, it will be a lot more fun :)

**Comment by LaurentMazare** [comment]
Closing now that stable diffusers 2 has been supported for some time.
