### ISSUE TITLE
Support DPM MultiStep Scheduler

### ISSUE THREAD

**Issue by ajmwagar** [LaurentMazare/diffusers-rs#17]
Would be great to have support for the DPM MultiStep Scheduler. 

Diffusers recommends using it as it's the fastest scheduler at the moment: https://huggingface.co/docs/diffusers/v0.9.0/en/api/pipelines/stable_diffusion_2#available-checkpoints

Link to diffusers python implementation:

https://github.com/huggingface/diffusers/blob/v0.9.0/src/diffusers/schedulers/scheduling_dpmsolver_multistep.py#L57

**Comment by mspronesti** [comment]
I'm working on it. I will open a PR soon:)

**Comment by mspronesti** [comment]
I guess this issue can be closed now.

**Comment by LaurentMazare** [comment]
As mentioned by @mspronesti this has been added (as well as many other schedulers :) ).
