### ISSUE TITLE
Fatal error LNK1120: 2 unresolved externals

### ISSUE THREAD

**Issue by JohnAlcatraz** [LaurentMazare/diffusers-rs#27]
I'm trying to run this again, but it does not compile. I have cloned this repo with
`git clone https://github.com/LaurentMazare/diffusers-rs.git`
and then run
`cargo run --example stable-diffusion --features clap -- --prompt "A rusty robot holding a fire torch."`
like the readme says. It then compiles everything, until it reaches
` Compiling diffusers v0.2.0`
and then fails with
```error: linking with `link.exe` failed: exit code: 1120```
and the actual issue it complains about is this:

```
  = note:    Creating library C:\Other\StableDiffusion\Rust\Testing\fromgithub\diffusers-rs\target\debug\examples\stable_diffusion.lib and object C:\Other\StableDiffusion\Rust\Testing\fromgithub\diffusers-rs\target\debug\examples\stable_diffusion.exp
          libtorch_sys-56f4e8e25c10d9d7.rlib(torch_api.o) : error LNK2001: unresolved external symbol __imp___tls_index_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
          libtorch_sys-56f4e8e25c10d9d7.rlib(torch_api.o) : error LNK2001: unresolved external symbol __imp___tls_offset_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
          C:\Other\StableDiffusion\Rust\Testing\fromgithub\diffusers-rs\target\debug\examples\stable_diffusion.exe : fatal error LNK1120: 2 unresolved externals
```

          
Am I doing something wrong, or is the current main branch maybe just not compiling? I know I was able to run this fine in the past.

**Comment by LaurentMazare** [comment]
This is an issue with libtorch and the visual studio compiler, see this [tch issue](https://github.com/LaurentMazare/tch-rs/issues/563) for more details but it seems to be fixed in visual studio 2022 17.4.3.

**Comment by JohnAlcatraz** [comment]
Ah, thanks! I'm indeed still on 17.4.1, so I'll update it now and see if that fixes it.

**Comment by JohnAlcatraz** [comment]
Updating to 17.4.1 indeed fixed this. Thanks!
