### ISSUE TITLE
Automate weights setup

### ISSUE THREAD

**Issue by mspronesti** [LaurentMazare/diffusers-rs#4]
Hello @LaurentMazare and thanks for this awesome Rust implementation!
I'm playing around with it but I find the overall setup a little boring as it requires to switch from bash to python a couple of times and to place things in the right directory. 

Therefore, I wrote a shell script to automate the whole process. Might you be interested in such a contribution (e.g. under a `scripts` folder in the root of the repository) ? 
Cheers :smiley:

**Comment by JohnAlcatraz** [comment]
Please make a PR with that, even if it's not getting merged, it would still allow people to use it. I'd really like to be able to use it :)

**Comment by mspronesti** [comment]
Hi @JohnAlcatraz, I'm happy you are interested in this contribution. I think I will wait for a reply from @LaurentMazare and if he is not interested in this contribution I will just upload the script here :+1:

**Comment by LaurentMazare** [comment]
If you already have a small script to do this, certainly feel free to make a PR. That said don't put too much effort in it, I have some hope that we can tweak things to use the original weight files directly, and if it doesn't work out I'll check the license and package the weights on huggingface as per #8 , so the script won't be necessary anymore at that point (I should get around it this weekend).

**Comment by JohnAlcatraz** [comment]
> I have some hope that we can tweak things to use the original weight files directly, and if it doesn't work out I'll check the license and package the weights on huggingface as per https://github.com/LaurentMazare/diffusers-rs/issues/8 , so the script won't be necessary anymore at that point (I should get around it this weekend).

Any news on that? Would love to try this out, but I'm waiting for that first.

**Comment by LaurentMazare** [comment]
Using the original files directly from Rust is challenging because of some Python specific bits that they include that would require a Python runtime. I'll have a look at packaging the weights on huggingface but I would recommend using the script that @mspronesti added, `scripts/download_weights.sh` as this should grab the original weights and convert them for you automatically.

**Comment by mspronesti** [comment]
@LaurentMazare Maybe you could update the last section of the README, including the instruction to use the script instead of manual installation.

**Comment by JohnAlcatraz** [comment]
The script unfortunately does not work for me. It opens a cmd window for 0.1 seconds, that closes before I can read what it says, and is not downloading or converting anything.

**Comment by JohnAlcatraz** [comment]
I managed to get it to work by running it on the WSL on Windows. But it's not really a nice way to do it that way, the average user does not know how to use the WSL. It took quite a while to install all the stuff that was required for it in the WSL.
