### ISSUE TITLE
Loading of text embeddings in pt format?

### ISSUE THREAD

**Issue by Emulator000** [LaurentMazare/diffusers-rs#59]
I was wondering on how is possible to load embeddings in `pt` format?

If I try to load it as Clip I get an error:
```
Expected Tensor but got GenericDict
```

Also it would be nice to support more than one external text embedding.

**Comment by LaurentMazare** [comment]
The `.pt` format is somewhat supported but with some limitations, see https://github.com/LaurentMazare/tch-rs/issues/595#issuecomment-1364108766 for some details.
When it comes to loading weights, the easy ways I could see all involve pre-processing the weights in python.
- You can try saving the weights to a new `.pt` or `.bin` file via
```python
torch.save(dict(model.state_dict()), "mymodel.bin")
```
- Alternatively, you can save the tensors using the `.safetensors` format which should hopefully work out of the box when loading them.
- A last alternative is to store the tensors is a .npz file and then use `tensor-tools` to convert this to a `.ot` file, see some details [here](https://github.com/LaurentMazare/diffusers-rs/blob/4ce3c0477e98080db776cf0f50ac8b1720eeb633/examples/stable-diffusion/main.rs#L20).

**Comment by LaurentMazare** [comment]
Closing this, hopefully the explanations above were enough to fix the issue.
