### ISSUE TITLE
Please consider packaging the final weights

### ISSUE THREAD

**Issue by JohnAlcatraz** [LaurentMazare/diffusers-rs#8]
In the readme you mention:

> If there is some interest in having the final weight files available, open an issue and we could consider packaging them.

Having to run a bunch of python code first to convert the weights manually is quite annoying, so yes, please consider packaging them in an easy download in the right format. 

I'd really like to use this, but doing all those steps manually for converting the weights is too difficult.

**Comment by Ryu1845** [comment]
I'd suggest hosting them on huggingface for consistency with the original diffusers library

**Comment by LaurentMazare** [comment]
The weights in `.ot` format are now available directly from a [dedicated huggingface repo](https://huggingface.co/lmz/rust-stable-diffusion-v1-5), including weights for the inpainting model. Hopefully this should make trying this crate easier.
